--SCHEMA
CREATE USER INVENTORY_MANAGE IDENTIFIED BY SECRET;
GRANT CONNECT, ALL privilege TO INVENTORY_MANAGE;

--Tables
CREATE TABLE FLOOR
  (
    "FLOOR_ID"           NUMBER(18,0) NOT NULL ENABLE,
    "BUILDING_NAME"      VARCHAR2(80 CHAR),
	"OFFICE_NAME"      VARCHAR2(80 CHAR),
	"DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6),
   CONSTRAINT "PK_FLOOR_ID" PRIMARY KEY ("FLOOR_ID") ENABLE
 );
 
 CREATE TABLE RACK
  (
    "RACK_ID"           NUMBER(18,0) NOT NULL ENABLE,
    "RACK_POSITION"      VARCHAR2(80 CHAR),
	"RACK_DESCRIPTION"      VARCHAR2(80 CHAR),
	"FLOOR_ID"           NUMBER(18,0) NOT NULL ENABLE,
	"DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6),
   CONSTRAINT "PK_RACK_ID" PRIMARY KEY ("RACK_ID") ENABLE,
   CONSTRAINT "FK_FLOOR_ID" FOREIGN KEY ("FLOOR_ID") REFERENCES "FLOOR" ("FLOOR_ID") ENABLE
 );
  
CREATE TABLE CATEGORIES
  (
    "CATEGORY_ID"          NUMBER(18,0) NOT NULL ENABLE,
	"CATEGORY_NAME"        VARCHAR2(80 CHAR),
	"RACK_ID"              NUMBER(18,0) NOT NULL ENABLE,
    "PARENT_CATEGORY_ID"   NUMBER(18,0),
	"DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6), 
	CONSTRAINT "PK_CATEGORY_ID" PRIMARY KEY ("CATEGORY_ID") ENABLE,
    CONSTRAINT "FK_RACK_ID" FOREIGN KEY ("RACK_ID") REFERENCES "RACK" ("RACK_ID") ENABLE,
	CONSTRAINT "FK_PARENT_ID" FOREIGN KEY ("PARENT_CATEGORY_ID") REFERENCES "CATEGORIES" ("CATEGORY_ID") ENABLE
);


CREATE TABLE UNITS
  (
    "UNIT_ID"          NUMBER(18,0) NOT NULL ENABLE,
	"UNIT_NAME"         VARCHAR2(80 CHAR) NOT NULL ENABLE,
	"UNIT_DESC"         NUMBER(18,0) ,
    CONSTRAINT "PK_UNINT_ID" PRIMARY KEY ("UNIT_ID")
);

CREATE TABLE PRODUCT
  (
    "PRODUCT_ID"         NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NAME"       VARCHAR2(80 CHAR),
	"CATEGORY_ID"            NUMBER(18,0) NOT NULL ENABLE,
	"PRICE"              NUMBER(18,0) NOT NULL ENABLE,
	"QUANTITY"           NUMBER(18,0) NOT NULL ENABLE,
    "UNIT_ID"               NUMBER(18,0) NOT NULL ENABLE,
	"DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6), 
	
	CONSTRAINT "PK_PRODUCT_ID" PRIMARY KEY ("PRODUCT_ID") ENABLE,
    CONSTRAINT "FK_CATEGORY_ID" FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORIES" ("CATEGORY_ID") ENABLE,
	CONSTRAINT "FK_UNIT_ID" FOREIGN KEY ("UNIT_ID") REFERENCES "UNITS" ("UNIT_ID") ENABLE
);


CREATE TABLE USERS
  (
    "USER_ID"         NUMBER(18,0) NOT NULL ENABLE,
	"USER_NAME"       VARCHAR2(80 CHAR),
	"USER_CONTACT"            NUMBER(18,0) NOT NULL ENABLE,
	"USER_EMAIL"              NUMBER(18,0) NOT NULL ENABLE,
	"IS_ACTIVE"        NUMBER(1,0),
	"DOB" DATE,
	"DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6), 
	
	CONSTRAINT "PK_USER_ID" PRIMARY KEY ("USER_ID") ENABLE
);

CREATE TABLE ADDRESS
  (
  	"ADDRESS_ID"         NUMBER(18,0) NOT NULL ENABLE,  
  	"USER_ID"         NUMBER(18,0) NOT NULL ENABLE,
  	"HOUSE_NO"     		   VARCHAR2(80 CHAR),
	"STREET"     		   VARCHAR2(80 CHAR),
	"CITY"      		   VARCHAR2(80 CHAR),
	"STATE"                VARCHAR2(80 CHAR),
    "COUNTRY"              VARCHAR2(80 CHAR),
	"ID_ADDRESS_TYPE"       NUMBER(5,0) NOT NULL ENABLE,
    "DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6), 
	CONSTRAINT "PK_ADDRESS_ID" PRIMARY KEY ("ADDRESS_ID") ENABLE,
    CONSTRAINT "FK_ADD_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID") ENABLE
);

CREATE TABLE USER_INDENTIFICATIONS
 (
 	"IDENTIFICATION_ID"  NUMBER(18,0) NOT NULL ENABLE,
 	"USER_ID"    NUMBER (18,0) NOT NULL ENABLE,
 	"IDENTIFICATION"  VARCHAR2(80 CHAR),
 	"IS_ACTIVE"        NUMBER(1,0),
 	"DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6), 
	CONSTRAINT "PK_INDENTIFICATION_ID" PRIMARY KEY ("IDENTIFICATION_ID") ENABLE,
    CONSTRAINT "FK_INDENT_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID") ENABLE
 );


CREATE TABLE USER_CREDENTIALS
 (
 	"CREDENTIAL_ID"  NUMBER(18,0) NOT NULL ENABLE,
 	"USER_ID"    NUMBER (18,0) NOT NULL ENABLE,
 	"CREDENTIALS"  VARCHAR2(80 CHAR),
 	"IS_ACTIVE"        NUMBER(1,0),
 	"DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6), 
	CONSTRAINT "PK_CREDENTIAL_ID" PRIMARY KEY ("CREDENTIAL_ID") ENABLE,
    CONSTRAINT "FK_CRED_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID") ENABLE
 );

CREATE TABLE ROLES
  (
    "ROLE_ID"         NUMBER(18,0) NOT NULL ENABLE,
	"STR_ROLE"       VARCHAR2(80 CHAR),
	"CATEGORY_ID"            NUMBER(18,0) NOT NULL ENABLE,
	"ROLE_DESC"             VARCHAR2(100 CHAR),
	"DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6), 
	CONSTRAINT "PK_ROLE_ID" PRIMARY KEY ("ROLE_ID") ENABLE
);    

CREATE TABLE USER_ROLES
  (
    "ROLE_ID"         NUMBER(18,0) NOT NULL ENABLE,
	"USER_ID"        NUMBER(18,0) NOT NULL ENABLE,
	"DAT_CREATION" TIMESTAMP (6),
    "DAT_LAST_UPDATE" TIMESTAMP (6), 
	
	CONSTRAINT "FK_USER_ROLE_ROLE_ID" FOREIGN KEY ("ROLE_ID")REFERENCES "ROLES" ("ROLE_ID") ENABLE,
	CONSTRAINT "FK_USR_ROLE_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID") ENABLE
);    